export type AppRoute = {
  id: string;
  label: string;
  path: string;
  section: "investor" | "experto";
  role: "investor" | "admin" | "fiduciario";
  icon: string;
  status: "active" | "simulated" | "planned";
  description: string;
};

export const ROUTE_REGISTRY: AppRoute[] = [
  // ═══════════════════════════════════════════════════
  // INVERSOR: Flujo del Holder / Comprador
  // ═══════════════════════════════════════════════════
  {
    id: "investor-portfolio",
    label: "Mi Portafolio",
    path: "/dashboard/investor",
    section: "investor",
    role: "investor",
    icon: "wallet",
    status: "active",
    description: "Visualiza tus fracciones inmobiliarias y rendimiento.",
  },
  {
    id: "investor-wallet",
    label: "Billetera (Fondeo)",
    path: "/dashboard/investor/wallet",
    section: "investor",
    role: "investor",
    icon: "banknote",
    status: "active",
    description: "Inyecta capital vía MercadoPago para adquirir propiedades.",
  },
  {
    id: "investor-marketplace",
    label: "Marketplace P2P",
    path: "/dashboard/investor/marketplace",
    section: "investor",
    role: "investor",
    icon: "activity",
    status: "active",
    description: "Mercado secundario de fracciones RWA.",
  },
  {
    id: "investor-borrow",
    label: "Préstamos DeFi",
    path: "/dashboard/investor/borrow",
    section: "investor",
    role: "investor",
    icon: "scale",
    status: "active",
    description: "Solicita liquidez en USD usando tus tokens como colateral.",
  },
  {
    id: "investor-learn",
    label: "Aprende",
    path: "/dashboard/investor/learn",
    section: "investor",
    role: "investor",
    icon: "book-open",
    status: "active",
    description: "Centro educativo sobre Tokenización y RWA.",
  },
  {
    id: "investor-governance",
    label: "Gobernanza",
    path: "/dashboard/investor/governance",
    section: "investor",
    role: "investor",
    icon: "scale",
    status: "active",
    description: "Participa en las decisiones de la comunidad.",
  },
  {
    id: "investor-staking",
    label: "Staking",
    path: "/dashboard/investor/staking",
    section: "investor",
    role: "investor",
    icon: "lock",
    status: "active",
    description: "Bloquea tokens para ganar Multiplicador de Voto y Yield.",
  },
  {
    id: "investor-kyc",
    label: "Verificación KYC",
    path: "/dashboard/investor/kyc",
    section: "investor",
    role: "investor",
    icon: "file-signature",
    status: "active",
    description: "Sube tus documentos de identidad para cumplimiento.",
  },
  {
    id: "investor-settings",
    label: "Mi Perfil",
    path: "/dashboard/investor/settings",
    section: "investor",
    role: "investor",
    icon: "users",
    status: "active",
    description: "Ajustes de cuenta, seguridad y notificaciones.",
  },

  // ═══════════════════════════════════════════════════
  // ADMINISTRADOR: Consola Bancaria (Checker / Tesorería)
  // ═══════════════════════════════════════════════════
  {
    id: "admin-dashboard",
    label: "Panel Admin",
    path: "/dashboard/admin",
    section: "experto",
    role: "admin",
    icon: "layout-dashboard",
    status: "active",
    description: "Visión operativa global del sistema.",
  },
  {
    id: "admin-approvals",
    label: "Aprobaciones",
    path: "/dashboard/admin/approvals",
    section: "experto",
    role: "admin",
    icon: "shield",
    status: "active",
    description: "Bandeja para aprobar Fondeos, Retiros y KYC.",
  },
  {
    id: "admin-kyc",
    label: "Revisión KYC",
    path: "/dashboard/admin/kyc",
    section: "experto",
    role: "admin",
    icon: "file-signature",
    status: "active",
    description: "Revisión manual de documentos de identidad.",
  },
  {
    id: "admin-landbank",
    label: "Bóvedas RWA",
    path: "/dashboard/admin/landbank",
    section: "experto",
    role: "admin",
    icon: "landmark",
    status: "active",
    description: "Control sobre propiedades y circulante de tokens.",
  },
  {
    id: "admin-treasury",
    label: "Tesorería Central",
    path: "/dashboard/admin/treasury",
    section: "experto",
    role: "admin",
    icon: "layout-dashboard",
    status: "active",
    description: "Bóveda Central, yield y liquidación.",
  },
  {
    id: "admin-governance",
    label: "Emisor de Propuestas",
    path: "/dashboard/admin/governance",
    section: "experto",
    role: "admin",
    icon: "file-text",
    status: "active",
    description: "Publicar propuestas de gobernanza a la comunidad.",
  },
  {
    id: "admin-audit",
    label: "Ledger Inmutable",
    path: "/dashboard/admin/audit",
    section: "experto",
    role: "admin",
    icon: "file-search",
    status: "active",
    description: "Registro inmutable de transacciones (Double-Entry).",
  },
  {
    id: "admin-fideicomiso",
    label: "Fideicomiso",
    path: "/dashboard/fideicomiso",
    section: "experto",
    role: "admin",
    icon: "pen-tool",
    status: "active",
    description: "Control de operaciones legales subyacentes.",
  },
];
