export type AppRoute = {
  id: string;
  label: string;
  path: string;
  section: "investor" | "experto";
  role: "public" | "investor" | "admin" | "fiduciario" | "operator";
  icon: string;
  status: "active" | "simulated" | "pending_credentials" | "pending_foundry" | "disabled" | "planned";
  description: string;
  primaryAction?: string;
  secondaryAction?: string;
};

export const ROUTE_REGISTRY: AppRoute[] = [
  // --- Public / Investor Flow ---
  {
    id: "demo-start",
    label: "Demo Start",
    path: "/demo/start",
    section: "investor",
    role: "public",
    icon: "play-square",
    status: "active",
    description: "Flujo guiado de la demo.",
  },
  {
    id: "dashboard-investor",
    label: "Panel Inversor",
    path: "/dashboard/investor",
    section: "investor",
    role: "investor",
    icon: "wallet",
    status: "active",
    description: "Panel principal del inversor (ProRataLandCard).",
    primaryAction: "Simular Adquisición",
  },
  {
    id: "investor-genesis",
    label: "Ronda Genesis",
    path: "/dashboard/investor/genesis",
    section: "investor",
    role: "investor",
    icon: "history",
    status: "active",
    description: "Tracking de intentos de flujo Genesis.",
  },
  {
    id: "investor-marketplace",
    label: "Marketplace P2P",
    path: "/dashboard/investor/marketplace",
    section: "investor",
    role: "investor",
    icon: "activity",
    status: "active",
    description: "Mercado secundario de participaciones PACHA.",
  },
  {
    id: "investor-ledger",
    label: "Ledger PACHA",
    path: "/dashboard/investor/ledger",
    section: "investor",
    role: "investor",
    icon: "list",
    status: "active",
    description: "Historial on-chain simulado de transferencias.",
  },
  {
    id: "investor-disclosures",
    label: "Disclaimers",
    path: "/dashboard/investor/disclosures",
    section: "investor",
    role: "investor",
    icon: "alert-triangle",
    status: "active",
    description: "Términos y condiciones del entorno simulado.",
  },

  // --- Modo Experto / Admin / Technical ---
  {
    id: "demo-showcase",
    label: "Showcase / Libre",
    path: "/demo/showcase",
    section: "experto",
    role: "public",
    icon: "play-square",
    status: "active",
    description: "Hub central de la Demo Local.",
    primaryAction: "Enter Flow",
  },
  {
    id: "demo-walkthrough",
    label: "Walkthrough",
    path: "/demo/walkthrough",
    section: "experto",
    role: "public",
    icon: "book-open",
    status: "active",
    description: "Paso a paso de la inicialización de la Demo.",
  },
  {
    id: "demo-design-system",
    label: "Design System",
    path: "/demo/design-system",
    section: "experto",
    role: "public",
    icon: "palette",
    status: "active",
    description: "Playground de componentes Mission Control.",
  },
  {
    id: "demo-scenarios",
    label: "Escenarios",
    path: "/demo/scenarios",
    section: "experto",
    role: "public",
    icon: "test-tube",
    status: "active",
    description: "Panel para simular diferentes contextos de usuario.",
  },
  {
    id: "demo-legal",
    label: "Portal Legal",
    path: "/demo/legal",
    section: "experto",
    role: "public",
    icon: "scale",
    status: "active",
    description: "Disclaimers y términos del entorno Sandbox.",
  },
  {
    id: "dashboard-admin",
    label: "Consola Admin",
    path: "/dashboard/admin",
    section: "experto",
    role: "admin",
    icon: "layout-dashboard",
    status: "active",
    description: "Panel general de administración.",
  },
  {
    id: "admin-users",
    label: "Usuarios y KYC",
    path: "/dashboard/admin/users",
    section: "experto",
    role: "admin",
    icon: "users",
    status: "active",
    description: "Gestión profunda de usuarios y KYC simulado.",
  },
  {
    id: "admin-audit",
    label: "Auditoría",
    path: "/dashboard/admin/audit",
    section: "experto",
    role: "admin",
    icon: "file-search",
    status: "active",
    description: "Visualizador premium de logs de auditoría.",
  },
  {
    id: "admin-integrations",
    label: "Integraciones",
    path: "/dashboard/admin/integrations",
    section: "experto",
    role: "admin",
    icon: "activity",
    status: "active",
    description: "Gestión del estado de conexiones externas.",
  },
  {
    id: "admin-token-orders",
    label: "Órdenes Token",
    path: "/dashboard/admin/token-orders",
    section: "experto",
    role: "admin",
    icon: "shopping-cart",
    status: "active",
    description: "Supervisión de órdenes de adquisición simuladas.",
  },
  {
    id: "dashboard-fideicomiso",
    label: "Fideicomiso",
    path: "/dashboard/fideicomiso",
    section: "experto",
    role: "fiduciario",
    icon: "shield",
    status: "active",
    description: "Firma y control de operaciones RWA.",
    primaryAction: "Firmar Operación",
  },
  {
    id: "fideicomiso-operations",
    label: "Operaciones pendientes",
    path: "/dashboard/fideicomiso/operations",
    section: "experto",
    role: "fiduciario",
    icon: "file-signature",
    status: "active",
    description: "Operaciones Multi-Sig pendientes de firma.",
  },
  {
    id: "fideicomiso-signatures",
    label: "Firmas",
    path: "/dashboard/fideicomiso/signatures",
    section: "experto",
    role: "fiduciario",
    icon: "pen-tool",
    status: "active",
    description: "Auditoría del estado del quórum.",
  },
  {
    id: "fideicomiso-legal-backing",
    label: "Respaldo Legal",
    path: "/dashboard/fideicomiso/legal-backing",
    section: "experto",
    role: "fiduciario",
    icon: "landmark",
    status: "active",
    description: "Detalles del inmueble y emisión subyacente.",
  },
  {
    id: "demo-operator",
    label: "Consola Operador",
    path: "/demo/operator",
    section: "experto",
    role: "operator",
    icon: "terminal",
    status: "active",
    description: "Herramientas de entorno local (Doctor, Reset, Seed).",
    primaryAction: "Reset DB",
  },
  {
    id: "demo-integrations",
    label: "Estado de Integraciones",
    path: "/demo/integrations",
    section: "experto",
    role: "operator",
    icon: "puzzle",
    status: "pending_credentials",
    description: "Estado técnico de conexiones (MP, Foundry).",
  },
];
