export type AppRoute = {
  id: string;
  label: string;
  path: string;
  section: "investor" | "experto" | "client";
  role: "investor" | "admin" | "fiduciario" | "client";
  icon: string;
  status: "active" | "simulated" | "planned" | "quarantined";
  description: string;
};

export const ROUTE_REGISTRY: AppRoute[] = [
  {
    id: "investor-portfolio",
    label: "Mis participaciones",
    path: "/dashboard/investor",
    section: "investor",
    role: "investor",
    icon: "wallet",
    status: "active",
    description: "Proyectos que cofinanciás y su estado.",
  },
  {
    id: "investor-wallet",
    label: "Capital",
    path: "/dashboard/investor/wallet",
    section: "investor",
    role: "investor",
    icon: "banknote",
    status: "active",
    description: "Aportes de capital. No es una wallet de tokens.",
  },
  {
    id: "investor-learn",
    label: "Cómo funciona",
    path: "/dashboard/investor/learn",
    section: "investor",
    role: "investor",
    icon: "book-open",
    status: "active",
    description: "Cofinanciamiento, landbanking y trazabilidad.",
  },
  {
    id: "investor-kyc",
    label: "Verificación KYC",
    path: "/dashboard/investor/kyc",
    section: "investor",
    role: "investor",
    icon: "file-signature",
    status: "active",
    description: "Documentos de identidad para operar.",
  },
  {
    id: "investor-settings",
    label: "Mi perfil",
    path: "/dashboard/investor/settings",
    section: "investor",
    role: "investor",
    icon: "users",
    status: "active",
    description: "Cuenta, seguridad y notificaciones.",
  },
  {
    id: "investor-marketplace",
    label: "Mercado P2P",
    path: "/dashboard/investor/marketplace",
    section: "investor",
    role: "investor",
    icon: "activity",
    status: "quarantined",
    description: "Cuarentena: secondary de fracciones.",
  },
  {
    id: "investor-borrow",
    label: "Préstamos DeFi",
    path: "/dashboard/investor/borrow",
    section: "investor",
    role: "investor",
    icon: "scale",
    status: "quarantined",
    description: "Cuarentena: préstamos contra tokens.",
  },
  {
    id: "investor-governance",
    label: "Gobernanza",
    path: "/dashboard/investor/governance",
    section: "investor",
    role: "investor",
    icon: "scale",
    status: "quarantined",
    description: "Cuarentena: DAO.",
  },
  {
    id: "investor-staking",
    label: "Staking",
    path: "/dashboard/investor/staking",
    section: "investor",
    role: "investor",
    icon: "lock",
    status: "quarantined",
    description: "Cuarentena: staking de tokens.",
  },

  {
    id: "admin-dashboard",
    label: "Panel admin",
    path: "/dashboard/admin",
    section: "experto",
    role: "admin",
    icon: "layout-dashboard",
    status: "active",
    description: "Operación de la plataforma.",
  },
  {
    id: "admin-approvals",
    label: "Aprobaciones",
    path: "/dashboard/admin/approvals",
    section: "experto",
    role: "admin",
    icon: "shield",
    status: "active",
    description: "KYC, aportes y documentos.",
  },
  {
    id: "admin-kyc",
    label: "Revisión KYC",
    path: "/dashboard/admin/kyc",
    section: "experto",
    role: "admin",
    icon: "file-signature",
    status: "active",
    description: "Identidad de inversores y clientes.",
  },
  {
    id: "admin-landbank",
    label: "Proyectos",
    path: "/dashboard/admin/landbank",
    section: "experto",
    role: "admin",
    icon: "landmark",
    status: "active",
    description: "Landbanking, venta y renta. No es bóveda de tokens.",
  },
  {
    id: "admin-audit",
    label: "Trazabilidad",
    path: "/dashboard/admin/audit",
    section: "experto",
    role: "admin",
    icon: "file-search",
    status: "active",
    description: "Quién hizo qué, cuándo y con qué documento.",
  },
  {
    id: "admin-fideicomiso",
    label: "Fideicomiso",
    path: "/dashboard/fideicomiso",
    section: "experto",
    role: "admin",
    icon: "pen-tool",
    status: "active",
    description: "Validación documental interna.",
  },
  {
    id: "admin-treasury",
    label: "Tesorería token",
    path: "/dashboard/admin/treasury",
    section: "experto",
    role: "admin",
    icon: "layout-dashboard",
    status: "quarantined",
    description: "Cuarentena: tesorería on-chain.",
  },
  {
    id: "admin-governance",
    label: "Gobernanza admin",
    path: "/dashboard/admin/governance",
    section: "experto",
    role: "admin",
    icon: "file-text",
    status: "quarantined",
    description: "Cuarentena: propuestas DAO.",
  },

  {
    id: "client-home",
    label: "Mi operación",
    path: "/dashboard/client",
    section: "client",
    role: "client",
    icon: "home",
    status: "active",
    description: "Comprador o arrendatario del inmueble.",
  },
  {
    id: "client-kyc",
    label: "KYC",
    path: "/dashboard/client/kyc",
    section: "client",
    role: "client",
    icon: "file-signature",
    status: "active",
    description: "Identidad del comprador o arrendatario.",
  },
  {
    id: "client-listings",
    label: "Ofertas",
    path: "/dashboard/client/ofertas",
    section: "client",
    role: "client",
    icon: "shopping-cart",
    status: "planned",
    description: "Lotes, unidades y alquileres. Fase 5.",
  },
  {
    id: "client-reservations",
    label: "Reservas",
    path: "/dashboard/client/reservas",
    section: "client",
    role: "client",
    icon: "list",
    status: "planned",
    description: "Fase 5.",
  },
  {
    id: "client-contracts",
    label: "Contratos",
    path: "/dashboard/client/contratos",
    section: "client",
    role: "client",
    icon: "file-signature",
    status: "planned",
    description: "Fase 5.",
  },
  {
    id: "client-payments",
    label: "Pagos",
    path: "/dashboard/client/pagos",
    section: "client",
    role: "client",
    icon: "banknote",
    status: "planned",
    description: "Fase 5.",
  },
];
